---
kind: pipeline
name: "Push on master"

concurrency: 
  limit: 2

  steps:
  - name: "Verify & build"
    image: node:10.16.0
    commands: 
    - npm install
    - npm test
    - npm build

trigger:
  event:
    - push
    - pull